### PR TITLE
Add colloquial area and sublocality to return obj; Add package-lock.json

### PR DESCRIPTION
**Pull request by prichey**

### CODE REVIEW

**Comment by mkoryak** [comment]
Looks good, do you want me to cut a new version from this?

**Comment by prichey** [comment]
I actually have another commit I'd like to add, just a sec

**Comment by prichey** [comment]
I want to make sure my check in component finder works as expected. I'm not entirely sure I grok the logic of the previous check.

https://github.com/mkoryak/address-validator/pull/10/commits/8524d33ec89d121edd174652c56734458e1b81ee#diff-b5aaaa3d001c394049c3e25228dca54fR175

**Comment by prichey** [comment]
Other than that, feel free to merge and push. Probably makes sense to release as a new version. Let me know if I can do anything else. Thanks!

**Comment by mkoryak** [comment]
Ok I'll try to do this tomorrow. I need to also be sure you didn't break it
:)

**Comment by prichey** [comment]
Yup, sounds good. 😅

**Comment by mkoryak** [comment]
Sorry, things got busy at work and I forgot all about this PR. 

Its in now, do you want me to publish a new version to npm?

**Comment by prichey** [comment]
No problem. I've been using my own fork for a project that I'm working on but since the PR is merged I'd say go ahead if everything looks good to you.

Thanks!

**Pull request merged**
